#!/bin/bash

# This build file has been generated by c_build

# Set alias for python if on Unix
if [[ "$(uname)" != "Windows_NT" ]]; then
    alias python=python3
fi

# Run validation script with both script names
if [ -f "./c_build/validate_temp_files.sh" ]; then
    bash ./c_build/validate_temp_files.sh "bootstrap.sh"
    bash ./c_build/validate_temp_files.sh "$(basename "$0")"
else
    echo "Validation script not found."
fi

# Update c_build repository
pushd "./c_build" > /dev/null
git fetch origin -q
git reset --hard origin/main -q
git pull -q
popd > /dev/null

# Run build script with debug or release depending on argument
if [ "$1" = "-debug" ]; then
    python -B -m c_build_script --execution_type "BUILD" --build_type "debug"
else
    python -B -m c_build_script --execution_type "BUILD" --build_type "release"
fi
