#!/bin/bash

# This build file has been generated by c_build

# Set python alias if on Unix
if [[ "$(uname)" != "Windows_NT" ]]; then
    alias python=python3
fi

# Run validation script for bootstrap.sh and this script
if [ -f "./c_build/validate_temp_files.sh" ]; then
    bash ./c_build/validate_temp_files.sh "bootstrap.sh"
    bash ./c_build/validate_temp_files.sh "$(basename "$0")"
else
    echo "Validation script not found."
    exit 1
fi

# Pull the latest version of c_build
pushd "./c_build" > /dev/null
git fetch origin -q
git reset --hard origin/main -q
git pull -q
popd > /dev/null

# Clean build with either debug or release config
if [ "$1" = "-debug" ]; then
    python -B -m c_build_script --execution_type "CLEAN" --build_type "debug"
else
    python -B -m c_build_script --execution_type "CLEAN" --build_type "release"
fi
