# This build file has been generated by C-Build and is specifically for the MSVC compiler cl

$libs = ""
$source_paths = "./source"
$include_paths = ""
$lib_paths = ""

#build default, ckit, or ckg

./C-BUILD/cl/build.ps1 $libs $lib_paths $source_paths $include_paths