# This build file has been generated by C-Build
if ($PSVersionTable.Platform -eq "Unix") {
    Set-Alias python python3
}

$current_file = Get-Item "."
$current_filename = $current_file.Name
$template_content = Get-Content -Path "./c-build/templates/$current_filename"

$current_content = Get-Content -Path $current_file.FullName
$differences = Compare-Object -ReferenceObject $current_content -DifferenceObject $template_content

if ($differences) {
    Write-Host "Template content for '$current_filename' is out of sync; you must run ./bootstrap.ps1" -ForegroundColor Red
    exit
}

$directoryPath = "./c-build"
$repositoryUrl = "https://github.com/superg3m/c-build.git"

if (-not (Test-Path -Path $directoryPath)) {
    Write-Output "Directory does not exist. Cloning the repository..."
    git clone $repositoryUrl
}

$bootstrapScriptPath = "$directoryPath/bootstrap.ps1"
if (Test-Path -Path $bootstrapScriptPath) {
    & $bootstrapScriptPath
} else {
    Write-Output "Bootstrap script not found at $bootstrapScriptPath"
}
