# This build file has been generated by C-Build

$configPath = "config.json"
$jsonData = Get-Content -Path $configPath -Raw | ConvertFrom-Json

$lib_name = $jsonData.'$lib_name'
$compile_time_defines = $jsonData.'$compile_time_defines'
$std_version = $jsonData.'$std_version'
$debug_build = $jsonData.'$debug_build'
$include_paths = $jsonData.'$include_paths'
$source_paths = $jsonData.'$source_paths'
$lib_paths = $jsonData.'$lib_paths'
$libs = $jsonData.'$libs'

Push-Location  ".\C-BUILD"
git stash
git stash drop
git pull
Pop-Location

./C-BUILD/$preset/$compiler_type/build_lib.ps1 `
    -lib_name $lib_name `
    -compile_time_defines $compile_time_defines `
    -std_version $std_version `
    -debug_build $debug_build `
    -include_paths $include_paths `
    -source_paths $source_paths `
    -lib_paths $lib_paths `
    -libs $libs