# This build file has been generated by C-Build

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$PSNativeCommandUseErrorActionPreference = $true

Push-Location  "./c-build"
git fetch origin > $null 2>&1
git reset --hard origin/main > $null 2>&1
git pull > $null 2>&1
Pop-Location

./c-build/$compiler_type/clean.ps1

# ok clean is not quiet right anymore you need to clean all build_procedures