# This build file has been generated by C-Build

$executable_name = ""

$include_paths = ""
$source_paths = "./source"

$lib_paths = ""
$libs = ""

$std_version = ""
$debug = $false; # compile with debug symbols
$generate_object_files = $false;

Push-Location  ".\C-BUILD"
git stash
git stash drop
git pull
Pop-Location

./C-BUILD/$preset/$compiler_type/clean_example.ps1 $executable_name $std_version $debug $generate_object_files $include_paths $source_paths $lib_paths $libs