# This build file has been generated by C-Build

Push-Location  ".\C-BUILD"
git stash
git stash drop
git pull
Pop-Location

./C-BUILD/$preset/$compiler_type/clean.ps1

# ok clean is not quiet right anymore you need to clean all build_procedures