# This build file has been generated by C-Build

$executable_name = ""

$include_paths = ""
$source_paths = "./source"

$lib_paths = ""
$libs = ""

$std_version = ""
$debug = $false; # compile with debug symbols
$generate_object_files = $false;

Push-Location  ".\C-BUILD"
git stash
git stash drop
git pull
Pop-Location

./C-BUILD/default/cl/normalize_path.ps1
