# This build file has been generated by C-Build



$configPath = "c_build_config.json"
$jsonData = Get-Content -Path $configPath -Raw | ConvertFrom-Json

$project_name = $jsonData.'$project_name'

$should_rebuild_project_dependencies = $jsonData.'$should_rebuild_project_dependencies'

Push-Location  "./c-build"
git fetch origin -q
git reset --hard origin/main -q
git pull -q
Pop-Location

Write-Host "|--------------- Started Building $project_name ---------------|" -ForegroundColor Blue
$timer = [Diagnostics.Stopwatch]::new() # Create a timer
$timer.Start() # Start the timer
foreach ($key in $jsonData.PSObject.Properties.Name) {
    $value = $jsonData.$key # value is json

    # If the value is json, iterate over its properties as well
    if ($value -is [PSCustomObject]) {     
        $build_procedure_name = $value.'$build_procedure_name'
        $should_build_procedure = $value.'$should_build_procedure'

        if ($should_build_procedure -eq $false) {
            Write-Host "Skipping $build_procedure_name..." -ForegroundColor Magenta
            continue
        }

        if(!(Test-Path -Path $key)) {
            Write-Host "Creating $key Directory"
            New-Item -Path $key -ItemType Directory -Force -ErrorAction SilentlyContinue > $null
        }

        # Serialize the $value object to a JSON string
        $jsonValue = $value | ConvertTo-Json -Compress

        foreach ($nestedKey in $value.PSObject.Properties.Name) {
            $nestedValue = $value.$nestedKey

            if ($nestedValue -is [Array]) {
                if (!$nestedValue) {
                    continue
                }
                
                Write-Host "[$build_procedure_name] depends on: " -ForegroundColor Blue
                foreach ($element in $nestedValue) {
                    Write-Host "  - $element" -ForegroundColor Blue

                    if(!(Test-Path -Path $element)) {
                        Write-Host "missing $element"
                        git clone https://github.com/superg3m/$element.git
                    } else {
                        Push-Location $element
                        git fetch origin -q
                        git reset --hard origin/main -q
                        git pull -q
                        Pop-Location
                    }
                    
                    Push-Location "$element"
                    if(!(Test-Path -Path "c-build")) {
                        git clone "https://github.com/superg3m/c-build.git"
                    } else {
                        Push-Location  "./c-build"
                        git fetch origin -q
                        git reset --hard origin/main -q
                        git pull -q
                        Pop-Location
                    }

                    if ($should_rebuild_project_dependencies -eq $true) {
                        if (Test-Path -Path "c_build_is_build.flag") {
                            Remove-Item -Path "c_build_is_build.flag" > $null
                        }
                    }
                    
                    if (Test-Path -Path "c_build_is_build.flag") {
                        Write-Host "$element Depedency Already Build Skipping..." -ForegroundColor Magenta
                    } else {
                        ./c-build/bootstrap.ps1 -compiler_type $compiler_type
                        ./build.ps1
                        New-Item -Path "c_build_is_build.flag" > $null
                    }
                    
                    Pop-Location
                }
                Write-Host ""
            }
        }

        ./c-build/$compiler_type/clean_procedure.ps1 -project $project -build_procedure $build_procedure_name
        ./c-build/$compiler_type/build_procedure.ps1 -project $project
    }
}
$timer.Stop()
Write-Host "|--------------- Build time: $($timer.Elapsed.TotalSeconds)s ---------------|" -ForegroundColor Blue

